### ISSUE TITLE
implementation guidelines wireguard

### ISSUE THREAD

**Issue by mrpops2ko** [intel/intel-ipsec-mb#148]
hi i am attempting to introduce this cryto accellerator through linux

the guide current covers the installation but i am struggling to find documentation on how to implement this via wireguard as the default traffic accellerator

is this on by default or would i need to declare this specific library somewhere in the configuration? 

im not sure if this is the best place for this issue, and it might be more suitable in the wireguard specific repo 

edit: additionally would i require the installation of DPDK libraries? 

edit2: [this guide / whitepaper Intel® AVX-512 and Intel® QAT - Accelerate WireGuard
Processing with Intel® Xeon® D-2700 Processor](https://networkbuilders.intel.com/docs/networkbuilders/intel-avx-512-and-intel-qat-accelerate-wireguard-processing-with-intel-xeon-d-2700-processor-technology-guide-1647024663.pdf ) offers some basic guidance it seems? 
edit3: seems maybe the [VPP Wireguard](https://s3-docs.fd.io/vpp/22.02/developer/plugins/wireguard.html) method might be the easiest to do?

**Comment by tkanteck** [comment]
Hi, thanks for reaching out.

I just wanted to point to the paper that you added in edit2.
VPP Wireguard is probably the easiest to do.

Please note that in order to use intel-ipsec-mb-library in VPP, crypto_ipsecmb plugin needs to be selected as crypto provider in the configuration (this may not always be the case). Library installation is not required for VPP, it includes versioned intel-ipsec-mb library code inside VPP.

**Comment by tkanteck** [comment]
Let me close this issue. Feel free to re-open as needed.
