### ISSUE TITLE
NASM version requirement should be 2.14

### ISSUE THREAD

**Issue by Jean-Mick** [intel/intel-ipsec-mb#26]
Hello,
I can see invalid opcode error when building on Ubuntu 18.04 where NASM is 2.13.02:
avx512/gcm_vaes_avx512.asm:4960: error: invalid combination of opcode and operand
It compiles fine with NASM 2.14, I think this version is required for vaesenc instructions. 
Please confirm && update the doc!
Thanks,
Jean-Mickael

**Comment by tkanteck** [comment]
Hello Jean-Mick,

Unfortunately this is expected because we started to use new VAES and VPCLMULQDQ in the code :) Please note NASM version requirement changed in README and minimum version required now is 2.13.03 or newer.

I think Ubuntu has already newer package for NASM available. If not please look at NASM web site https://www.nasm.us/pub/nasm/releasebuilds/?C=M;O=D

Thanks,
Tomasz

**Comment by Jean-Mick** [comment]
My point is that README should tell >=2.14 instead of 2.13.03.

**Comment by tkanteck** [comment]
2.13.03 will also do but 2.13.02 will not

**Comment by Jean-Mick** [comment]
Oh ok got it now...thanks. And I confirm 2.13.03 works.
